//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarupaSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BangDreamResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BangDreamResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GarupaSimulator.Properties.BangDreamResources", typeof(BangDreamResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Afterglow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Afterglow {
            get {
                return ResourceManager.GetString("Afterglow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Badge Event に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BadgeEvent {
            get {
                return ResourceManager.GetString("BadgeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Challenge Live Event に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChallengeEvent {
            get {
                return ResourceManager.GetString("ChallengeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello, Happy World! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelloHappyWorld {
            get {
                return ResourceManager.GetString("HelloHappyWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mission Live Event に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MissionEvent {
            get {
                return ResourceManager.GetString("MissionEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pastel * Palettes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PastelPalettes {
            get {
                return ResourceManager.GetString("PastelPalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poppin&apos;Party に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PoppinParty {
            get {
                return ResourceManager.GetString("PoppinParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roselia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Roselia {
            get {
                return ResourceManager.GetString("Roselia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Live Goals Event に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TryEvent {
            get {
                return ResourceManager.GetString("TryEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VS Live Event に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VsEvent {
            get {
                return ResourceManager.GetString("VsEvent", resourceCulture);
            }
        }
    }
}
